//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SHIFTBRITEARDUINO_H_
#define _SHIFTBRITEARDUINO_H_

#include <TinyCLR_Interop.h>
struct Library_ShiftBriteArduino_ShiftBriteArduino_CommandPacket
{
    static const int FIELD__<CommandMode>k__BackingField = 1;
    static const int FIELD__<RedCommand>k__BackingField = 2;
    static const int FIELD__<GreenCommand>k__BackingField = 3;
    static const int FIELD__<BlueCommand>k__BackingField = 4;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_ComplexBehaviorManager
{
    static const int FIELD___rgbManager = 1;
    static const int FIELD___logger = 2;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_DebugRoutines
{
    static const int FIELD__pin0 = 1;
    static const int FIELD__pin1 = 2;
    static const int FIELD__pin2 = 3;
    static const int FIELD__pin3 = 4;
    static const int FIELD__pin4 = 5;
    static const int FIELD__pin5 = 6;
    static const int FIELD__pin6 = 7;
    static const int FIELD__pin7 = 8;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_FrameworkShims_OutputPort
{
    static const int FIELD___internalPort = 1;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_IO_PortLayout
{
    static const int FIELD__<DataPorts>k__BackingField = 1;
    static const int FIELD__<LatchPort>k__BackingField = 2;
    static const int FIELD__<ClockPort>k__BackingField = 3;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_IO_PortManager
{
    static const int FIELD___portLayout = 1;
    static const int FIELD___logger = 2;
    static const int FIELD___latchDelayOffset = 3;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_LedColor
{
    static const int FIELD___red = 1;
    static const int FIELD___green = 2;
    static const int FIELD___blue = 3;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_Logger
{
    static const int FIELD___ledPort = 1;
    static const int FIELD___message = 2;


    //--//

};

struct Library_ShiftBriteArduino_ShiftBriteArduino_RgbManager
{
    static const int FIELD___rgbArray = 1;
    static const int FIELD___portManager = 2;
    static const int FIELD___numBanks = 3;
    static const int FIELD___numChannels = 4;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ShiftBriteArduino;

#endif  //_SHIFTBRITEARDUINO_H_
